const express = require('express');
const app = express();
const port = 3001;

// tokens to be generated by a single chat response
const totalTokens = 10_000;


// Middleware to log incoming requests
app.use((req, res, next) => {
  console.log('\n=== Incoming Request ===');
  // console.log(`Incoming request: ${req.method} ${req.url}`);
  // console.log(`Request payload: ${req.body}`);
  console.log(`${req.method} ${req.url}`);
  console.log('Headers:', JSON.stringify(req.headers, null, 2));
  console.log('Body:', JSON.stringify(req.body, null, 2));
  next();
});

app.use(express.json());

/**
 * @swagger
 * /info:
 *   get:
 *     summary: Info endpoint
 *     responses:
 *       200:
 *         description: A successful response
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 models:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Model'
 */
app.get('/info', (req, res) => {
  const models = [
    {
      name: "code-model",
      max_input_length: 8191,
      max_total_tokens: 8192,
      description: "Code completion model by TNG.",
      capabilities: {
        "chat": "none",
        "code": "partial",
        "fim": "full",
      },
    },
    {
      name: "chat-model",
      max_input_length: 131069,
      max_total_tokens: 131070,
      description: "A model with general chat capability.",
      capabilities: {
        "chat": "full",
        "code": "full",
        "fim": "none",
      }
    },
    {
      name: "chat-model-ten",
      max_input_length: 131069,
      max_total_tokens: 131070,
      description: "A model with general chat capability. Responds with 10 tokens per second.",
      capabilities: {
        "chat": "full",
        "code": "full",
        "fim": "none",
      }
    },
    {
      name: "chat-model-hundred",
      max_input_length: 131069,
      max_total_tokens: 131070,
      description: "A model with general chat capability. Responds with 100 tokens per second.",
      capabilities: {
        "chat": "full",
        "code": "full",
        "fim": "none",
      }
    },
    {
      name: "chat-model-thousand",
      max_input_length: 131069,
      max_total_tokens: 131070,
      description: "A model with general chat capability. Responds with 1000 tokens per second.",
      capabilities: {
        "chat": "full",
        "code": "full",
        "fim": "none",
      }
    }
  ];

  res.json({ models });
});

app.get('/v1/models', (req, res) => {
  const models = [
    { id: "deepseek-ai/DeepSeek-R1", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "Qwen/Qwen2.5-Coder-32B-Instruct", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "Qwen/Qwen2.5-VL-72B-Instruct", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "mistralai/Mistral-Small-24B-Instruct-2501", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "mistralai/Mixtral-8x22B-Instruct-v0.1", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "meta-llama/Llama-3.3-70B-Instruct", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "/tngtech/Qwen2.5-Coder-32B-finetune-WIP", object: "model", created: 1739831212, owned_by: "TNG" },
    { id: "/tngtech/tng-codepilot", object: "model", created: 1739831212, owned_by: "TNG" },
  ];

  res.json({ object: "list", data: models });
});

/**
 * @swagger
 * /v1/chat/completions:
 *   post:
 *     summary: Chat completions endpoint
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               model:
 *                 type: string
 *                 description: The model to use (ten, hundred, thousand)
 *               streaming:
 *                 type: boolean
 *                 description: Whether to stream the response
 *     responses:
 *       200:
 *         description: A successful response
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 response:
 *                   type: string
 *                   description: The response from the chat completions endpoint
 *           text/event-stream:
 *             schema:
 *               type: string
 *               description: Streamed response from the chat completions endpoint
 */
app.post('/v1/chat/completions', (req, res) => {
  console.log("Post request headers:");
  console.log(req.headers);
  console.log("Post request body:");
  console.log(req.body);
  const { model, stream } = req.body;

  if (stream) {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    const tokenSpeed = {
      'chat-model-ten': 1000 / 10, // 10 tokens per second
      'chat-model-hundred': 1000 / 100, // 100 tokens per second
      'chat-model-thousand': 1000 / 1000 // 1000 tokens per second
    };

    const speed = tokenSpeed[model] || 1000 / 1000;
    let sentTokens = 0;
    const loremIpsum = ('lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.').repeat(1000);

    const chunkSize = 10; // adjust this value to control the chunk size
    const sendTokens = () => {
      if (sentTokens < totalTokens) {
        const chunk = loremIpsum.slice(sentTokens, sentTokens + chunkSize);
        const response = {
          status: 200,
          id: 'chatcmpl-' + Math.random().toString(36).substr(2, 10),
          cached: false,
          server_version: '0.31.0',
          object: 'chat.completion.chunk',
          created: Math.floor(Date.now() / 1000),
          model: model,
          usage: {
            prompt_tokens: -1,
            completion_tokens: -1,
            total_tokens: -1
          },
          choices: [{
            index: 0,
            delta: {
              role: 'assistant',
              content: chunk
            },
            finish_reason: null,
            logprobs: null
          }]
        };
        res.write(`data: ${JSON.stringify(response)}\n\n`);
        sentTokens += chunkSize;
        setTimeout(sendTokens, speed);
      } else {
        const finalResponse = {
          status: 200,
          id: 'chatcmpl-' + Math.random().toString(36).substr(2, 10),
          cached: false,
          server_version: '0.31.0',
          object: 'chat.completion.chunk',
          created: Math.floor(Date.now() / 1000),
          model: model,
          usage: {
            prompt_tokens: -1,
            completion_tokens: -1,
            total_tokens: -1
          },
          choices: [{
            index: 0,
            delta: {
              role: 'assistant',
              content: ''
            },
            finish_reason: 'length',
            logprobs: null
          }]
        };
        res.write(`data: ${JSON.stringify(finalResponse)}\n\n`);
        res.end();
      }
    };

    sendTokens();
  } else {
    res.json({ response: 'lorem ipsum...'.repeat(100) });
  }
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
});